<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-PN9KDUT" failures="1" tests="2" name="Error Validations Test" time="41.292" errors="0" timestamp="2024-06-07T12:48:29 GET">
  <testcase classname="Levan.SeleniumFramework.ErrorValidationsTest" name="loginErrorValidation" time="1.064"/>
  <testcase classname="Levan.SeleniumFramework.ErrorValidationsTest" name="productErrorValidation" time="23.879">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Levan.SeleniumFramework.ErrorValidationsTest.productErrorValidation(ErrorValidationsTest.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- productErrorValidation -->
</testsuite> <!-- Error Validations Test -->
